# Generated by Django 4.0.4 on 2022-07-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fupresystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedbacks',
        ),
    ]
