# Generated by Django 4.0.4 on 2022-09-07 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fupresystem', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='applications',
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
